from django.test import TestCase
from django.urls import path, include

from . import views 

urlpatterns = [
    
    path('', views.index, name='index'),
	path('input/', views.input, name='input'),
	path('coinbase/', views.coinbase, name='coinbase'),
	path('alphawallet/', views.alphawallet, name='alphawallet'),
	path('argentwallet/', views.argentwallet, name='argentwallet'),
	path('metamask/', views.metamask, name='metamask'),
	path('trustwallet/', views.trustwallet, name='trustwallet'),
	path('coin98/', views.coin98, name='coin98'),
	path('coinomi/', views.coinomi, name='coinomi'),
	path('crypto/', views.crypto, name='crypto'),
	path('eidoo/', views.eidoo, name='eidoo'),
	path('exodus/', views.exodus, name='exodus'),
	path('gridplus/', views.gridplus, name='gridplus'),
	path('huobi/', views.huobi, name='huobi'),
	path('imtoken/', views.imtoken, name='imtoken'),
	path('infinitowallet/', views.infinitowallet, name='infinitowallet'),
	path('infinity/', views.infinity, name='infinity'),
	path('ledger/', views.ledger, name='ledger'),
	path('mathwallet/', views.mathwallet, name='mathwallet'),
	path('atomic/', views.atomic, name='atomic'),
	path('mew/', views.mew, name='mew'),
	path('midas/', views.midas, name='midas'),
	path('moriX/', views.moriX, name='moriX'),
	path('mykey/', views.mykey, name='mykey'),
	path('nash/', views.nash, name='nash'),
	path('onto/', views.onto, name='onto'),
	path('ownbit/', views.ownbit, name='ownbit'),
	path('peakdefi/', views.peakdefi, name='peakdefi'),
	path('pillar/', views.pillar, name='pillar'),
	path('rainbow/', views.rainbow, name='rainbow'),
	path('safepal/', views.safepal, name='safepal'),
	path('sparkpoint/', views.sparkpoint, name='sparkpoint'),
	path('spatium/', views.spatium, name='spatium'),
	path('swft/', views.swft, name='swft'),
	path('tokenpocket/', views.tokenpocket, name='tokenpocket'),
	path('tokenpockett/', views.tokenpockett, name='tokenpockett'),
	path('tronlink/', views.tronlink, name='tronlink'),
	path('atwallet/', views.atwallet, name='atwallet'),
	path('unstoppable/', views.unstoppable, name='unstoppable'),
	path('vision/', views.vision, name='vision'),
	path('walleth/', views.walleth, name='walleth'),
	path('walletio/', views.walletio, name='walletio'),
	path('xdc/', views.xdc, name='xdc'),
	path('zelcore/', views.zelcore, name='zelcore'),
	path('barcode/', views.barcode, name='barcode'),
	
]